Add xsl for converting PAGE XML to hOCR
OCR-D/format-converters pull request #3
Opened 2019-01-23 12:39 UTC by mhug

2019-01-24 14:33 UTC, kba commented on page2hocr.xsl
> +	<xsl:template name="bbox_or_poly">
Just remembered https://github.com/kba/ocr-xsl

2019-01-24 14:37 UTC, kba requested changes
Looks good. Minimal but should be enough to work. The coordinate parsing could be more concise IMHO. Consider https://github.com/kba/ocr-xsl/blob/581b509a4aa62d9ee67e80de1dae4035ff11fbfa/xsl-functions/ocr.bbox.xsl#L44-L76

2019-03-06 12:03 UTC, kba approved these changes

2019-03-06 12:03 UTC, merged

2024-05-02 10:42 UTC, stweil commented on page2hocr.xsl
> +		<div class="cr_carea" title="{$bbox_poly}">
Where does the class name `cr_carea` come from? It caused confusions (see https://github.com/UB-Mannheim/ocr-fileformat/issues/183), and I could not find it in the hOCR specification.